server:
  port: 8082
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eureka:8070/eureka

management:
  endpoint:
    env:
      post:
        enabled: true
    web:
      exposure:
        include: "env"

spring:
  data:
    redis:
      database: 0
      host: redis_container
      port: 6379
      password: redis_password
      timeout: 60000