server:
  port: 8072

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka:8070/eureka

spring:
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
  main:
    web-application-type: reactive

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus, gateway
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true
    gateway:
      enabled: true

