spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    consumer:
      group-id: test-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      missing-topics-fatal: false
    properties:
      spring:
        json:
          trusted:
            packages: "my.project.orderservice.messaging.events"

  # Эта строка подменяется в @SpringBootTest:
  # bootstrap-servers: ${spring.embedded.kafka.brokers}

logging:
  level:
    root: WARN
    org.springframework.kafka: INFO
    my.project.orderservice: DEBUG
