server:
  port: 8083
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/nanomarket_db
    username: root
    password: root
  data:
    jdbc:
      dialect: postgresql
  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: validate

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka:8070/eureka

management:
  endpoint:
    env:
      post:
        enabled: true
resilience4j.circuitbreaker:
  instances:
    orderServiceUpdate:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 5
      ringBufferSizeInHalfOpenState: 3
      waitDurationInOpenState: 10s
      failureRateThreshold: 50
#      recordExceptions:
#        - org.springframework.web.client.HttpServerErrorException
#        - java.io.IOException
#        - java.util.concurrent.TimeoutException
#        - org.springframework.web.client.ResourceAccessException



#resilience4j:
#  circuitbreaker:
#    configs:
#      default:
#        registerHealthIndicator: true
#        slidingWindowSize: 100
#        failureRateThreshold: 50
#        waitDurationInOpenState: 5s
#    instances:
#      externalService:
#        baseConfig: default
#        slidingWindowSize: 50
#        failureRateThreshold: 60
