server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/nanomarket_db
    username: root
    password: root
  data:
    jdbc:
      dialect: postgresql
    redis:
      database: 1
      host: redis_cache
      port: 6379
      password: redis_password
      timeout: 60000
  jpa:
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/liquibase/changelog-master.yaml
  cache:
    type: redis

  kafka:
    producer:
      bootstrap-servers: kafka-1:9092,kafka-2:9094,kafka-3:9096
    consumer:
      bootstrap-servers: kafka-1:9092,kafka-2:9094,kafka-3:9096
      group-id: order-service-group
      auto-offset-reset: earliest
    topic:
      orderCreated: order-created-events-topic
      orderCancelled: order-cancelled-events-topic
      productReserved: product-reserved-events-topic
      productOutOfStock: product-out-of-stock-events-topic

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

minio:
  MINIO_ROOT_USER: minioaccesskey
  MINIO_ROOT_PASSWORD: miniosecretkey
  endpoint: http://minio:9000
  region: us-east-1



eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka:8070/eureka

management:
  endpoint:
    env:
      post:
        enabled: true
