spring:
  kafka:
    bootstrap-servers: kafka-1:9092,kafka-2:9094,kafka-3:9096
    producer:
      bootstrap-servers: kafka-1:9092,kafka-2:9094,kafka-3:9096
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      delivery-timeout-ms: 10000
      linger-ms: 0
      request-timeout-ms: 5000
      enable-idempotence: true

    consumer:
      bootstrap-servers: kafka-1:9092,kafka-2:9094,kafka-3:9096
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: saga-service-group
      properties:
        spring.json.trusted.packages: "my.project.events"
    topic:
      orderEvents: order-events-topic
      orderCommands: order-commands-topic
      productEvents: product-events-topic
      productCommands: product-commands-topic